// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApnHyvq-rRCj5BraPKeC-Gqueqj0f5Tb8',
    appId: '1:508079311764:web:a657939f62ac4b8cd31d81',
    messagingSenderId: '508079311764',
    projectId: 'handmadeproject-4933e',
    authDomain: 'handmadeproject-4933e.firebaseapp.com',
    storageBucket: 'handmadeproject-4933e.appspot.com',
    measurementId: 'G-J49VK4QBSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_UTvkHsssm_g-rmSd8x6GXlraFMEju0M',
    appId: '1:508079311764:android:7c2458d48faa7f6fd31d81',
    messagingSenderId: '508079311764',
    projectId: 'handmadeproject-4933e',
    storageBucket: 'handmadeproject-4933e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgHG0kPitrLnTnNi8lPg3aa3J-4pz2TeM',
    appId: '1:508079311764:ios:81a39a78164b3bf2d31d81',
    messagingSenderId: '508079311764',
    projectId: 'handmadeproject-4933e',
    storageBucket: 'handmadeproject-4933e.appspot.com',
    iosBundleId: 'com.example.dashPortHandMade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgHG0kPitrLnTnNi8lPg3aa3J-4pz2TeM',
    appId: '1:508079311764:ios:c43b5f57c372c07ed31d81',
    messagingSenderId: '508079311764',
    projectId: 'handmadeproject-4933e',
    storageBucket: 'handmadeproject-4933e.appspot.com',
    iosBundleId: 'com.example.dashPortHandMade.RunnerTests',
  );
}
